import { Cylinder, notificationSetting, User, Circle } from '../types';

export const cylinders: Cylinder[] =
    [
        {
            id: 1,
            creatorId: 1,
            name: 'Pro gas home',
            currentWeight: 2,
            initialWeight: 3,
            active: true,
            provider: 'PRO GAS',
            sensorId: 'ar3f92PdDKd',
            lastRefill: '2021-01-01',
            circle: 10,
        },
        {
            id: 2,
            creatorId: 3,
            name: 'Pro gas office',
            currentWeight: 5,
            initialWeight: 6,
            active: true,
            provider: 'PRO GAS',
            sensorId: 'ar39o0PdDKd',
            lastRefill: '2021-01-01',
            circle: 8,
        },
        {
            id: 3,
            creatorId: 1,
            name: 'Pro gas factory',
            currentWeight: 7,
            initialWeight: 10,
            active: true,
            provider: 'PRO GAS',
            sensorId: 'ar39p1PdDKd',
            lastRefill: '2021-01-01',
            circle: 5,
        },
        {
            id: 4,
            creatorId: 4,
            name: 'K gas home',
            currentWeight: 1.8,
            initialWeight: 3,
            active: true,
            provider: 'PRO GAS',
            sensorId: 'p9r392PdDKd',
            lastRefill: '2021-01-01',
            circle: 1,
        },
        {
            id: 5,
            creatorId: 2,
            name: 'K gas School',
            currentWeight: 1.5,
            initialWeight: 3,
            active: true,
            provider: 'PRO GAS',
            sensorId: 'p9r392PdDKd',
            lastRefill: '2021-01-01',
            circle: 1,
        },
    ];

export const notificationSettings: notificationSetting[] = [
    {
        userId: 1,
        refillReminder: true,
        emailNotifications: true,
        pushNotifications: true,
        smsNotifications: false,
        newCircleCylinderAlert: true,
        newCircleMemberAlert: true,
        promotions: true,
        alertThreshold: 20,
    },
    {
        userId: 2,
        refillReminder: false,
        emailNotifications: true,
        pushNotifications: false,
        smsNotifications: false,
        newCircleCylinderAlert: true,
        newCircleMemberAlert: true,
        promotions: false,
        alertThreshold: 35,
    },
    {
        userId: 3,
        refillReminder: true,
        emailNotifications: true,
        pushNotifications: true,
        smsNotifications: true,
        newCircleCylinderAlert: true,
        newCircleMemberAlert: true,
        promotions: true,
        alertThreshold: 15,
    },
];

export const users: User[] = [
    {
        id: 1,
        name: 'John Doe',
        email: 'john@gmail.com',
        password: 'password',
    },
    {
        id: 2,
        name: 'Jane Doe',
        email: 'jane@gmail.com',
        password: '123',
    },
    {
        id: 3,
        name: 'Alice',
        email: 'alice@gmail.com',
        password: '1234',
    },
    {
        id: 4,
        name: 'Bob',
        email: 'bob@gmail.com',
        password: '12345',
    },
];

export const circles: Circle[] = [
    {
        id: 1,
        name: 'Family',
        cylinders: [cylinders[3], cylinders[4]],
        members: [users[0], users[1]],
        creator: users[0],
        joiningCode: 'FAMILY123',
    },
    {
        id: 2,
        name: 'Office',
        cylinders: [cylinders[1]],
        members: [users[0], users[3], users[4]],
        creator: users[0],
        joiningCode: 'OFFICE123',
    },
    {
        id: 3,
        name: 'Friends',
        cylinders: [cylinders[2]],
        members: [users[2], users[3]],
        creator: users[2],
        joiningCode: 'FRIENDS123',
    },
    {
        id: 4,
        name: 'School',
        cylinders: [cylinders[0]],
        members: [users[4], users[3]],
        creator: users[4],
        joiningCode: 'SCHOOL123',
    },
];

